export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const REQUEST_STARS_PENDING = 'REQUEST_STARS_PENDING';
export const REQUEST_STARS_SUCCESS = 'REQUEST_STARS_SUCCESS';
export const REQUEST_STARS_FAILED = 'REQUEST_STARS_FAILED';